### ISSUE TITLE
undefined method `[]' for nil:NilClass when trying to start Aurora instance

### ISSUE THREAD

**Issue by Guslington** [base2Services/cfn-library#19]
Version: 0.2.5
Command: start-environment

```
I, [2017-12-05T02:04:48.562103 #23593]  INFO -- : Starting environment dev
I, [2017-12-05T02:05:03.863631 #23593]  INFO -- : Starting resource xxx
I, [2017-12-05T02:05:03.863690 #23593]  INFO -- : Reading object configuration from s3://bucket.name/environment_data/resource/xxx/latest/config.json
W, [2017-12-05T02:05:03.912746 #23593]  WARN -- : Could not find configuration at s3://bucket.name/environment_data/resource/xxx/latest/config.json
I, [2017-12-05T02:05:04.014094 #23593]  INFO -- : RDS Instance xxx is already in available state
I, [2017-12-05T02:05:04.077181 #23593]  INFO -- : Instance xxx state: available, waiting for available
I, [2017-12-05T02:05:04.077292 #23593]  INFO -- : 1/4
I, [2017-12-05T02:05:19.170970 #23593]  INFO -- : Instance xxx state: available, waiting for available
I, [2017-12-05T02:05:19.171040 #23593]  INFO -- : 2/4
I, [2017-12-05T02:05:34.245654 #23593]  INFO -- : Instance xxx state: available, waiting for available
I, [2017-12-05T02:05:34.245713 #23593]  INFO -- : 3/4
I, [2017-12-05T02:05:49.301875 #23593]  INFO -- : Instance xxx state: available, waiting for available
I, [2017-12-05T02:05:49.301937 #23593]  INFO -- : 4/4
bundler: failed to load command: cfn_manage (/home/jenkins/.chefdk/gem/ruby/2.3.0/bin/cfn_manage)
NoMethodError: undefined method `[]' for nil:NilClass
  /home/jenkins/.chefdk/gem/ruby/2.3.0/gems/cfn_manage-0.2.5/lib/rds_start_stop_handler.rb:38:in `start'
  /home/jenkins/.chefdk/gem/ruby/2.3.0/gems/cfn_manage-0.2.5/lib/cf_start_stop_environment.rb:92:in `block in do_start_assets'
  /home/jenkins/.chefdk/gem/ruby/2.3.0/gems/cfn_manage-0.2.5/lib/cf_start_stop_environment.rb:83:in `each'
  /home/jenkins/.chefdk/gem/ruby/2.3.0/gems/cfn_manage-0.2.5/lib/cf_start_stop_environment.rb:83:in `do_start_assets'
  /home/jenkins/.chefdk/gem/ruby/2.3.0/gems/cfn_manage-0.2.5/lib/cf_start_stop_environment.rb:42:in `start_environment'
  /home/jenkins/.chefdk/gem/ruby/2.3.0/gems/cfn_manage-0.2.5/bin/cfn_manage.rb:94:in `<top (required)>'
  /home/jenkins/.chefdk/gem/ruby/2.3.0/gems/cfn_manage-0.2.5/bin/cfn_manage:2:in `require_relative'
  /home/jenkins/.chefdk/gem/ruby/2.3.0/gems/cfn_manage-0.2.5/bin/cfn_manage:2:in `<top (required)>'
  /home/jenkins/.chefdk/gem/ruby/2.3.0/bin/cfn_manage:22:in `load'
  /home/jenkins/.chefdk/gem/ruby/2.3.0/bin/cfn_manage:22:in `<top (required)>'
```

**Comment by toshke** [comment]
This has been resolved with `0.2.7` release.
